import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: { [key: string]: { [key: string]: string } } = {
  en: {
    appTitle: 'Multilingual Mandi',
    dashboard: 'Dashboard',
    chat: 'Chat',
    language: 'Language',
    priceQuery: 'Price Query',
    enterCropQuery: 'Enter crop query',
    queryPlaceholder: 'e.g., tomato price in Hyderabad',
    search: 'Search',
    searching: 'Searching...',
    currentPrices: 'Current Market Prices',
    market: 'Market',
    'trend.up': 'Rising',
    'trend.down': 'Falling',
    'trend.stable': 'Stable',
    negotiationChat: 'Negotiation Chat',
    session: 'Session',
    typeMessage: 'Type your message...',
    send: 'Send',
    translating: 'Translating...',
    voiceNotSupported: 'Voice input not supported in this browser',
    startListening: 'Start voice input',
    stopListening: 'Stop voice input',
    lastUpdate: 'Last updated',
    updated: 'Updated',
    refresh: 'Refresh',
    autoRefresh: 'Auto-refresh enabled',
    sending: 'Sending...',
    connected: 'Connected',
    disconnected: 'Disconnected',
    connecting: 'Connecting...',
    sessionInfo: 'Session Info',
    participants: 'Participants',
    startNewChat: 'Start New Chat',
    priceQuery: 'Price Query',
    systemMessage: 'System',
    aiAssistant: 'AI Assistant',
    translationFailed: 'Translation failed',
    confidence: 'Confidence',
    sources: 'sources',
    noSpeechDetected: 'No speech detected. Please try again.',
    microphoneError: 'Microphone access error. Please check permissions.',
    microphonePermissionDenied: 'Microphone permission denied. Please allow microphone access.',
    microphoneNotFound: 'No microphone found. Please connect a microphone.',
    networkError: 'Network error. Please check your connection.',
    serviceNotAllowed: 'Speech recognition service not allowed.',
    grammarError: 'Grammar recognition error.',
    languageNotSupported: 'Language not supported for voice input.',
    recognitionAborted: 'Speech recognition was aborted.',
    noSpeechMatch: 'No speech match found. Please try again.',
    initializationError: 'Failed to initialize voice input.',
    listeningTimeout: 'Listening timeout. Please try again.',
    startError: 'Failed to start voice input.',
    initializingVoice: 'Initializing voice input...',
  },
  hi: {
    appTitle: 'बहुभाषी मंडी',
    dashboard: 'डैशबोर्ड',
    chat: 'चैट',
    language: 'भाषा',
    priceQuery: 'मूल्य पूछताछ',
    enterCropQuery: 'फसल की पूछताछ दर्ज करें',
    queryPlaceholder: 'जैसे, हैदराबाद में टमाटर की कीमत',
    search: 'खोजें',
    searching: 'खोज रहे हैं...',
    currentPrices: 'वर्तमान बाजार मूल्य',
    market: 'बाजार',
    'trend.up': 'बढ़ रहा',
    'trend.down': 'गिर रहा',
    'trend.stable': 'स्थिर',
    negotiationChat: 'बातचीत चैट',
    session: 'सत्र',
    typeMessage: 'अपना संदेश टाइप करें...',
    send: 'भेजें',
    translating: 'अनुवाद कर रहे हैं...',
    voiceNotSupported: 'इस ब्राउज़र में वॉयस इनपुट समर्थित नहीं है',
    startListening: 'वॉयस इनपुट शुरू करें',
    stopListening: 'वॉयस इनपुट बंद करें',
    lastUpdate: 'अंतिम अपडेट',
    updated: 'अपडेट किया गया',
    refresh: 'रीफ्रेश',
    autoRefresh: 'ऑटो-रीफ्रेश सक्षम',
    sending: 'भेज रहे हैं...',
    connected: 'जुड़ा हुआ',
    disconnected: 'कनेक्शन टूटा',
    connecting: 'जुड़ रहे हैं...',
    sessionInfo: 'सत्र जानकारी',
    participants: 'प्रतिभागी',
    startNewChat: 'नई चैट शुरू करें',
    priceQuery: 'मूल्य पूछताछ',
    systemMessage: 'सिस्टम',
    aiAssistant: 'AI सहायक',
    translationFailed: 'अनुवाद असफल',
    confidence: 'विश्वास',
    sources: 'स्रोत',
    noSpeechDetected: 'कोई आवाज़ नहीं मिली। कृपया फिर से कोशिश करें।',
    microphoneError: 'माइक्रोफ़ोन एक्सेस त्रुटि। कृपया अनुमतियाँ जाँचें।',
    microphonePermissionDenied: 'माइक्रोफ़ोन अनुमति अस्वीकृत। कृपया माइक्रोफ़ोन एक्सेस की अनुमति दें।',
    microphoneNotFound: 'कोई माइक्रोफ़ोन नहीं मिला। कृपया माइक्रोफ़ोन कनेक्ट करें।',
    networkError: 'नेटवर्क त्रुटि। कृपया अपना कनेक्शन जाँचें।',
    serviceNotAllowed: 'वाक् पहचान सेवा की अनुमति नहीं है।',
    grammarError: 'व्याकरण पहचान त्रुटि।',
    languageNotSupported: 'वॉयस इनपुट के लिए भाषा समर्थित नहीं है।',
    recognitionAborted: 'वाक् पहचान रद्द कर दी गई।',
    noSpeechMatch: 'कोई वाक् मैच नहीं मिला। कृपया फिर से कोशिश करें।',
    initializationError: 'वॉयस इनपुट प्रारंभ करने में विफल।',
    listeningTimeout: 'सुनने का समय समाप्त। कृपया फिर से कोशिश करें।',
    startError: 'वॉयस इनपुट शुरू करने में विफल।',
    initializingVoice: 'वॉयस इनपुट प्रारंभ कर रहे हैं...',
  },
  te: {
    appTitle: 'బహుభాషా మండి',
    dashboard: 'డాష్‌బోర్డ్',
    chat: 'చాట్',
    language: 'భాష',
    priceQuery: 'ధర విచారణ',
    enterCropQuery: 'పంట విచారణను నమోదు చేయండి',
    queryPlaceholder: 'ఉదా., హైదరాబాద్‌లో టమాటో ధర',
    search: 'వెతకండి',
    searching: 'వెతుకుతున్నాం...',
    currentPrices: 'ప్రస్తుత మార్కెట్ ధరలు',
    market: 'మార్కెట్',
    'trend.up': 'పెరుగుతోంది',
    'trend.down': 'తగ్గుతోంది',
    'trend.stable': 'స్థిరంగా',
    negotiationChat: 'చర్చల చాట్',
    session: 'సెషన్',
    typeMessage: 'మీ సందేశాన్ని టైప్ చేయండి...',
    send: 'పంపండి',
    translating: 'అనువదిస్తున్నాం...',
    voiceNotSupported: 'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ మద్దతు లేదు',
    startListening: 'వాయిస్ ఇన్‌పుట్ ప్రారంభించండి',
    stopListening: 'వాయిస్ ఇన్‌పుట్ ఆపండి',
    lastUpdate: 'చివరిగా అప్‌డేట్ చేయబడింది',
    updated: 'అప్‌డేట్ చేయబడింది',
    refresh: 'రిఫ్రెష్',
    autoRefresh: 'ఆటో-రిఫ్రెష్ ప్రారంభించబడింది',
    sending: 'పంపుతున్నాం...',
    connected: 'కనెక్ట్ అయింది',
    disconnected: 'కనెక్షన్ తెగిపోయింది',
    connecting: 'కనెక్ట్ అవుతున్నాం...',
    sessionInfo: 'సెషన్ సమాచారం',
    participants: 'పాల్గొనేవారు',
    startNewChat: 'కొత్త చాట్ ప్రారంభించండి',
    priceQuery: 'ధర విచారణ',
    systemMessage: 'సిస్టమ్',
    aiAssistant: 'AI సహాయకుడు',
    translationFailed: 'అనువాదం విఫలమైంది',
    confidence: 'నమ్మకం',
    sources: 'మూలాలు',
    noSpeechDetected: 'ఎలాంటి మాట వినిపించలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    microphoneError: 'మైక్రోఫోన్ యాక్సెస్ లోపం. దయచేసి అనుమతులను తనిఖీ చేయండి.',
    microphonePermissionDenied: 'మైక్రోఫోన్ అనుమతి తిరస్కరించబడింది. దయచేసి మైక్రోఫోన్ యాక్సెస్‌ను అనుమతించండి.',
    microphoneNotFound: 'మైక్రోఫోన్ కనుగొనబడలేదు. దయచేసి మైక్రోఫోన్‌ను కనెక్ట్ చేయండి.',
    networkError: 'నెట్‌వర్క్ లోపం. దయచేసి మీ కనెక్షన్‌ను తనిఖీ చేయండి.',
    serviceNotAllowed: 'స్పీచ్ రికగ్నిషన్ సేవ అనుమతించబడలేదు.',
    grammarError: 'వ్యాకరణ గుర్తింపు లోపం.',
    languageNotSupported: 'వాయిస్ ఇన్‌పుట్ కోసం భాష మద్దతు లేదు.',
    recognitionAborted: 'స్పీచ్ రికగ్నిషన్ రద్దు చేయబడింది.',
    noSpeechMatch: 'ఎలాంటి స్పీచ్ మ్యాచ్ కనుగొనబడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    initializationError: 'వాయిస్ ఇన్‌పుట్ ప్రారంభించడంలో విఫలమైంది.',
    listeningTimeout: 'వినడం టైమ్‌అవుట్. దయచేసి మళ్లీ ప్రయత్నించండి.',
    startError: 'వాయిస్ ఇన్‌పుట్ ప్రారంభించడంలో విఫలమైంది.',
    initializingVoice: 'వాయిస్ ఇన్‌పుట్ ప్రారంభిస్తున్నాం...',
  },
  ta: {
    appTitle: 'பன்மொழி மண்டி',
    dashboard: 'டாஷ்போர்டு',
    chat: 'அரட்டை',
    language: 'மொழி',
    priceQuery: 'விலை விசாரணை',
    enterCropQuery: 'பயிர் விசாரணையை உள்ளிடவும்',
    queryPlaceholder: 'எ.கா., ஹைதராபாத்தில் தக்காளி விலை',
    search: 'தேடு',
    searching: 'தேடுகிறோம்...',
    currentPrices: 'தற்போதைய சந்தை விலைகள்',
    market: 'சந்தை',
    'trend.up': 'உயர்ந்து',
    'trend.down': 'குறைந்து',
    'trend.stable': 'நிலையான',
    negotiationChat: 'பேச்சுவார்த்தை அரட்டை',
    session: 'அமர்வு',
    typeMessage: 'உங்கள் செய்தியை தட்டச்சு செய்யவும்...',
    send: 'அனுப்பு',
    translating: 'மொழிபெயர்க்கிறோம்...',
    voiceNotSupported: 'இந்த உலாவியில் குரல் உள்ளீடு ஆதரிக்கப்படவில்லை',
    startListening: 'குரல் உள்ளீட்டைத் தொடங்கவும்',
    stopListening: 'குரல் உள்ளீட்டை நிறுத்தவும்',
    lastUpdate: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    updated: 'புதுப்பிக்கப்பட்டது',
    refresh: 'புதுப்பிக்கவும்',
    autoRefresh: 'தானியங்கி புதுப்பிப்பு இயக்கப்பட்டது',
    sending: 'அனுப்புகிறோம்...',
    connected: 'இணைக்கப்பட்டது',
    disconnected: 'இணைப்பு துண்டிக்கப்பட்டது',
    connecting: 'இணைக்கிறோம்...',
    sessionInfo: 'அமர்வு தகவல்',
    participants: 'பங்கேற்பாளர்கள்',
    startNewChat: 'புதிய அரட்டையைத் தொடங்கவும்',
    priceQuery: 'விலை விசாரணை',
    systemMessage: 'அமைப்பு',
    aiAssistant: 'AI உதவியாளர்',
    translationFailed: 'மொழிபெயர்ப்பு தோல்வியடைந்தது',
    confidence: 'நம்பிக்கை',
    sources: 'ஆதாரங்கள்',
    noSpeechDetected: 'எந்த பேச்சும் கண்டறியப்படவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    microphoneError: 'மைக்ரோஃபோன் அணுகல் பிழை. தயவுசெய்து அனுமதிகளை சரிபார்க்கவும்.',
    microphonePermissionDenied: 'மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது. தயவுசெய்து மைக்ரோஃபோன் அணுகலை அனுமதிக்கவும்.',
    microphoneNotFound: 'மைக்ரோஃபோன் கண்டுபிடிக்கப்படவில்லை. தயவுசெய்து மைக்ரோஃபோனை இணைக்கவும்.',
    networkError: 'நெட்வொர்க் பிழை. தயவுசெய்து உங்கள் இணைப்பை சரிபார்க்கவும்.',
    serviceNotAllowed: 'பேச்சு அங்கீகார சேவை அனுமதிக்கப்படவில்லை.',
    grammarError: 'இலக்கண அங்கீகார பிழை.',
    languageNotSupported: 'குரல் உள்ளீட்டிற்கு மொழி ஆதரிக்கப்படவில்லை.',
    recognitionAborted: 'பேச்சு அங்கீகாரம் நிறுத்தப்பட்டது.',
    noSpeechMatch: 'எந்த பேச்சு பொருத்தமும் கண்டுபிடிக்கப்படவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    initializationError: 'குரல் உள்ளீட்டை தொடங்குவதில் தோல்வி.',
    listeningTimeout: 'கேட்கும் நேரம் முடிந்தது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    startError: 'குரல் உள்ளீட்டை தொடங்குவதில் தோல்வி.',
    initializingVoice: 'குரல் உள்ளீட்டை தொடங்குகிறோம்...',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};